#!/usr/bin/env bash
# Generates src/build_info.ads with compile-time metadata
set -euo pipefail

VERSION="${VERSION:-$(git describe --tags --always --dirty 2>/dev/null || echo '1.0.0-dev')}"
COMMIT="${COMMIT:-$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')}"
BUILD_DATE="$(date -u +%Y-%m-%d)"
TARGET="${BUILD_TARGET:-native}"

cat > src/build_info.ads << EOF
--  Auto-generated by scripts/embed_version.sh — do not edit
package Build_Info is
   Version      : constant String := "$VERSION";
   Git_Commit   : constant String := "$COMMIT";
   Build_Date   : constant String := "$BUILD_DATE";
   Target_Triple : constant String := "$TARGET";
end Build_Info;
EOF

echo "Generated src/build_info.ads: $VERSION ($COMMIT) $BUILD_DATE $TARGET"
