#!/usr/bin/env bash
set -euo pipefail
LC_ALL=C

usage() {
  cat <<'EOF'
Usage: ./scripts/run_direct_competitor_harness.sh [--runs N] [--profile PROFILE] [--binder-mode MODE] [--output PATH] [--vericlaw-report PATH] [--zeroclaw-json PATH] [--nullclaw-json PATH] [--openclaw-json PATH] [--baseline PATH]

Builds a normalized side-by-side benchmark report for VeriClaw, ZeroClaw, and
NullClaw using equivalent scenario metadata. OpenClaw is included as
scorecard-only. ZeroClaw/NullClaw default to tests/*_v2_benchmark_ingest.json
when present.

If --vericlaw-report is not supplied, VeriClaw metrics are generated by reusing
./scripts/run_competitive_benchmarks.sh.
EOF
}

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output_path="${project_root}/tests/competitive_direct_benchmark_report.json"
vericlaw_report_path=""
zeroclaw_json_default="${project_root}/config/competitive_scorecards/zeroclaw_v2_scorecard.json"
if [[ -f "${project_root}/tests/zeroclaw_v2_benchmark_ingest.json" ]]; then
  zeroclaw_json_default="${project_root}/tests/zeroclaw_v2_benchmark_ingest.json"
fi
zeroclaw_json="${ZEROCLAW_JSON:-${zeroclaw_json_default}}"
nullclaw_json_default="${project_root}/config/competitive_scorecards/nullclaw_v2_scorecard.json"
if [[ -f "${project_root}/tests/nullclaw_v2_benchmark_ingest.json" ]]; then
  nullclaw_json_default="${project_root}/tests/nullclaw_v2_benchmark_ingest.json"
fi
nullclaw_json="${NULLCLAW_JSON:-${nullclaw_json_default}}"
openclaw_json="${OPENCLAW_JSON:-${project_root}/config/competitive_scorecards/openclaw_v2_scorecard.json}"
baseline_path="${BASELINE_PATH:-${project_root}/config/anywhere_v2_competitive_baseline.toml}"
runs=50
profile="${BUILD_PROFILE:-edge-speed}"
binder_mode="${BINDER_MODE:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --runs)
      [[ $# -ge 2 ]] || { echo "Missing value for --runs" >&2; exit 2; }
      runs="$2"
      shift 2
      ;;
    --profile)
      [[ $# -ge 2 ]] || { echo "Missing value for --profile" >&2; exit 2; }
      profile="$2"
      shift 2
      ;;
    --binder-mode)
      [[ $# -ge 2 ]] || { echo "Missing value for --binder-mode" >&2; exit 2; }
      binder_mode="$2"
      shift 2
      ;;
    --output)
      [[ $# -ge 2 ]] || { echo "Missing value for --output" >&2; exit 2; }
      output_path="$2"
      shift 2
      ;;
    --vericlaw-report)
      [[ $# -ge 2 ]] || { echo "Missing value for --vericlaw-report" >&2; exit 2; }
      vericlaw_report_path="$2"
      shift 2
      ;;
    --zeroclaw-json)
      [[ $# -ge 2 ]] || { echo "Missing value for --zeroclaw-json" >&2; exit 2; }
      zeroclaw_json="$2"
      shift 2
      ;;
    --nullclaw-json)
      [[ $# -ge 2 ]] || { echo "Missing value for --nullclaw-json" >&2; exit 2; }
      nullclaw_json="$2"
      shift 2
      ;;
    --openclaw-json)
      [[ $# -ge 2 ]] || { echo "Missing value for --openclaw-json" >&2; exit 2; }
      openclaw_json="$2"
      shift 2
      ;;
    --baseline)
      [[ $# -ge 2 ]] || { echo "Missing value for --baseline" >&2; exit 2; }
      baseline_path="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -n "${vericlaw_report_path}" && ! -f "${vericlaw_report_path}" ]]; then
  echo "Missing VeriClaw report: ${vericlaw_report_path}" >&2
  exit 1
fi
if [[ ! -f "${zeroclaw_json}" ]]; then
  echo "Missing ZeroClaw JSON: ${zeroclaw_json}" >&2
  exit 1
fi
if [[ ! -f "${nullclaw_json}" ]]; then
  echo "Missing NullClaw JSON: ${nullclaw_json}" >&2
  exit 1
fi
if [[ ! -f "${openclaw_json}" ]]; then
  echo "Missing OpenClaw JSON: ${openclaw_json}" >&2
  exit 1
fi
if [[ ! -f "${baseline_path}" ]]; then
  echo "Missing baseline config: ${baseline_path}" >&2
  exit 1
fi

tmp_vericlaw_report=""
if [[ -z "${vericlaw_report_path}" ]]; then
  tmp_vericlaw_report="$(mktemp)"
  vericlaw_report_path="${tmp_vericlaw_report}"
  vericlaw_args=(--runs "${runs}" --profile "${profile}" --output "${vericlaw_report_path}" --zeroclaw-json "${zeroclaw_json}" --nullclaw-json "${nullclaw_json}")
  if [[ -n "${binder_mode}" ]]; then
    vericlaw_args+=(--binder-mode "${binder_mode}")
  fi
  "${project_root}/scripts/run_competitive_benchmarks.sh" "${vericlaw_args[@]}" >/dev/null
fi

mkdir -p "$(dirname "${output_path}")"
python3 - "${vericlaw_report_path}" "${zeroclaw_json}" "${nullclaw_json}" "${openclaw_json}" "${baseline_path}" "${output_path}" "${project_root}" <<'PY'
import json
from datetime import datetime, timezone
import pathlib
import sys

vericlaw_report_path = pathlib.Path(sys.argv[1])
zeroclaw_path = pathlib.Path(sys.argv[2])
nullclaw_path = pathlib.Path(sys.argv[3])
openclaw_path = pathlib.Path(sys.argv[4])
baseline_path = pathlib.Path(sys.argv[5])
output_path = pathlib.Path(sys.argv[6])
project_root = pathlib.Path(sys.argv[7]).resolve()

with vericlaw_report_path.open("r", encoding="utf-8") as handle:
    vericlaw_report = json.load(handle)
with zeroclaw_path.open("r", encoding="utf-8") as handle:
    zeroclaw_payload = json.load(handle)
with nullclaw_path.open("r", encoding="utf-8") as handle:
    nullclaw_payload = json.load(handle)
with openclaw_path.open("r", encoding="utf-8") as handle:
    openclaw_payload = json.load(handle)
with baseline_path.open("rb") as handle:
    import tomllib
    baseline = tomllib.load(handle)

metric_ids = (
    "startup_ms",
    "idle_rss_mb",
    "dispatch_latency_p95_ms",
    "throughput_ops_per_sec",
    "binary_size_mb",
    "container_size_mb",
)
metric_directions = {
    "startup_ms": "lower_is_better",
    "idle_rss_mb": "lower_is_better",
    "dispatch_latency_p95_ms": "lower_is_better",
    "throughput_ops_per_sec": "higher_is_better",
    "binary_size_mb": "lower_is_better",
    "container_size_mb": "lower_is_better",
}


def as_number(value):
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    return None


def get_metric(payload, metric_id):
    if not isinstance(payload, dict):
        return None
    if metric_id in payload:
        return as_number(payload.get(metric_id))
    for key in ("performance", "metrics", "vericlaw"):
        nested = payload.get(key)
        if isinstance(nested, dict) and metric_id in nested:
            return as_number(nested.get(metric_id))
    return None


def get_section(payload, section):
    if not isinstance(payload, dict):
        return {}
    direct = payload.get(section)
    if isinstance(direct, dict):
        return direct
    scorecard = payload.get("scorecard")
    if isinstance(scorecard, dict):
        nested = scorecard.get(section)
        if isinstance(nested, dict):
            return nested
    return {}


def copy_optional_metadata(payload, normalized):
    if not isinstance(payload, dict):
        return
    for key in (
        "ingest_method",
        "ingest_source",
        "execution_feasibility",
        "performance_metric_sources",
        "metric_availability",
        "benchmark_ingest",
    ):
        if key in payload and payload[key] is not None:
            normalized[key] = payload[key]


def normalize_project(project, payload, scenario, source_path, peer_mode):
    source = pathlib.Path(source_path)
    try:
        source = source.resolve().relative_to(project_root)
    except ValueError:
        source = source
    normalized = {
        "project": project,
        "peer_mode": peer_mode,
        "source": str(source),
        "scenario": scenario,
        "performance": {metric: get_metric(payload, metric) for metric in metric_ids},
        "feature_parity": get_section(payload, "feature_parity"),
        "deployment_maturity": get_section(payload, "deployment_maturity"),
        "security_non_regression": get_section(payload, "security_non_regression"),
    }
    copy_optional_metadata(payload, normalized)
    return normalized


vericlaw_payload = vericlaw_report.get("vericlaw", {})
scenario = {
    "benchmark_runs": vericlaw_payload.get("benchmark_runs"),
    "build_profile": vericlaw_payload.get("build_profile"),
    "binder_mode": vericlaw_payload.get("binder_mode"),
    "measurement_mode": vericlaw_payload.get("measurement_mode"),
}
for key in ("target_platform", "host_platform", "platform_mismatch"):
    if key in vericlaw_payload:
        scenario[key] = vericlaw_payload.get(key)

vericlaw_scorecard = baseline.get("vericlaw_scorecard", {})
if not isinstance(vericlaw_scorecard, dict):
    vericlaw_scorecard = {}
vericlaw_feature = vericlaw_scorecard.get("feature_parity", {})
if not isinstance(vericlaw_feature, dict):
    vericlaw_feature = {}
vericlaw_deployment = vericlaw_scorecard.get("deployment_maturity", {})
if not isinstance(vericlaw_deployment, dict):
    vericlaw_deployment = {}
vericlaw_security = vericlaw_scorecard.get("security_non_regression", {})
if not isinstance(vericlaw_security, dict):
    vericlaw_security = {}

vericlaw_project = normalize_project(
    "vericlaw",
    vericlaw_payload,
    scenario,
    vericlaw_report_path,
    "pass_fail",
)
if vericlaw_feature:
    vericlaw_project["feature_parity"] = vericlaw_feature
if vericlaw_deployment:
    vericlaw_project["deployment_maturity"] = vericlaw_deployment
if vericlaw_security:
    vericlaw_project["security_non_regression"] = vericlaw_security

zeroclaw_project = normalize_project("zeroclaw", zeroclaw_payload, scenario, zeroclaw_path, "pass_fail")
nullclaw_project = normalize_project("nullclaw", nullclaw_payload, scenario, nullclaw_path, "pass_fail")
openclaw_project = normalize_project("openclaw", openclaw_payload, scenario, openclaw_path, "scorecard_only")
openclaw_project["performance"] = {}

comparisons = {}
for metric_id in metric_ids:
    vericlaw_value = vericlaw_project["performance"].get(metric_id)
    metric_comparison = {
        "direction": metric_directions.get(metric_id),
        "vericlaw": vericlaw_value,
        "peers": {},
    }
    for peer in (zeroclaw_project, nullclaw_project):
        peer_value = peer["performance"].get(metric_id)
        ratio = None
        if vericlaw_value is not None and peer_value not in (None, 0):
            ratio = vericlaw_value / peer_value
        metric_comparison["peers"][peer["project"]] = {
            "value": peer_value,
            "vericlaw_to_peer_ratio": ratio,
        }
    comparisons[metric_id] = metric_comparison

report = {
    "schema_version": "competitive-v2-direct-harness",
    "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "performance_peers": ["vericlaw", "zeroclaw", "nullclaw"],
    "scorecard_only_projects": ["openclaw"],
    "scenario": scenario,
    "projects": {
        "vericlaw": vericlaw_project,
        "zeroclaw": zeroclaw_project,
        "nullclaw": nullclaw_project,
        "openclaw": openclaw_project,
    },
    "comparisons": comparisons,
}

with output_path.open("w", encoding="utf-8") as handle:
    json.dump(report, handle, indent=2, sort_keys=True)
    handle.write("\n")
PY

if [[ -n "${tmp_vericlaw_report}" ]]; then
  rm -f "${tmp_vericlaw_report}"
fi

echo "direct-competitor-harness report: ${output_path}"
