--  Auto-generated by scripts/embed_version.sh — do not edit
--  This is the default for local development; CI overwrites it.
package Build_Info is
   Version      : constant String := "0.1.0-dev";
   Git_Commit   : constant String := "unknown";
   Build_Date   : constant String := "2026-02-27";
   Target_Triple : constant String := "native";
end Build_Info;
